language: node_js
node_js:
- '0.12'
sudo: false
env:
  matrix:
  - GROUP=
  global:
  - GHREPO=github.com/jupyter/jupyter-js-cells.git
  - secure: FWNQI+bgxYGPIPJeGK8kgaUcAUAqV/4rOodyKiIRueuiGg8oH1KbiR1zZH10TvzO16pFphaeuwD9anRTshq587wD40UeciXilr2DUrm9idxo0Aze0nTDBIakxOh1OMrvpooYq6n1FBGgMnIukbY9xy0FjizFl/5gGDSYhyT1K+y/C90YUMUKQt27MpB+TZBrJT6R2ulV/uBMTT2XiSkVOYv5WVdz3vFiEUrtJyC6fsADngvUgTMG/aE3zBRBULQa4R0S9rGXdlfzq8hnburjJkqlHDytFbYR0/RduZXt2bTQE+bblKuC9pPrYi20yyzJS1dqF7yksqIGBOyZMBfWyThU6Wn2hVPwRYt+Q2sT+XcpT4M86DJyKu48BBjumIlOML+/vcW547zcQQkvTc5fGeNGqR5LDsnG8ZWvwX/qsikVah09tp8KwPBM/876AMs1Zn4chRSWIzSgIPBI2jxOBBoHaNo5TIAyA+aLZfKnXAexKjtiKzpPnca2s4CbLBMDZDAWNUwEvNOlGpcqjT+EhuT6e8Wt0cZReIfPVp+CnAKyFkXWixDyDWeUQzMapUSyzlF4XPNJij9Gr6BP/eRqzX2FWOsVsdj5roYIWAt4B2k+YoUwcxcvjGMr+pnizzA/l7t/i7uevhXclfHrYZYuuBeoy16BW/6nisV+XS1JVGE=
install:
- bash scripts/travis_install.sh
script:
- bash scripts/travis_script.sh
after_success:
- bash scripts/travis_after_success.sh
